version: "3.7"
services:
  app:
    build: ./app
    links:
      - db
    ports:
      - "6080:5000"

  db:
    image: mysql:5.7.24
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro